### ISSUE TITLE
How to build 

### ISSUE THREAD

**Issue by moh1t** [esp-cpp/camera-streamer#5]
### Answers checklist.

- [X] I have read the documentation and the issue is not addressed there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hi 

I'm stuggling to build this in ESP-IDF on vs code. I manually downloaded and added all the linked dependencies like espp and esp32-camera, but it's erroring out.

Whats the correct way to build this?

**Comment by finger563** [comment]
When you say that you manually downloaded it - do you mean that you downloaded a zip of the repo and then manually copied in (from somewhere else?) the `espp` and `esp32-camera` dependencies? The `espp` repo itself has submodules, so you really should use `git submodule update --init --recursive` within your local copy of this repo (or clone it recursively from the start). 

I don't use VSCode, but the other thing to look at is what version of `ESP-IDF` you're building with within vscode.

If possible, can you provide some screenshots / logs of the errors you're getting when building?

**Comment by moh1t** [comment]
Thanks a lot for the guidance. I am build ni vs code via Esperiff IDF extension v1.6.4

Although I do get a couple of warnings/errors while compiling which I really don't underestand. The build still gets complete. I've added the errors below. Let me know if I should share the full log.

`[762/768] Building CXX object esp-idf/main/CMakeFiles/__idf_main.dir/main.cpp.obj
In file included from C:/Users/mohit/Documents/camera-streamer/components/espp/components/rtsp/include/jpeg_frame.hpp:4,
                 from C:/Users/mohit/Documents/camera-streamer/components/espp/components/rtsp/include/rtsp_server.hpp:15,
                 from C:/Users/mohit/Documents/camera-streamer/main/main.cpp:26:
C:/Users/mohit/Documents/camera-streamer/components/espp/components/rtsp/include/rtp_jpeg_packet.hpp: In member function 'bool espp::RtpJpegPacket::has_q_tables() const':
C:/Users/mohit/Documents/camera-streamer/components/espp/components/rtsp/include/rtp_jpeg_packet.hpp:100:54: warning: comparison is always true due to limited range of data type [-Wtype-limits]
  100 |   bool has_q_tables() const { return q_ >= 128 && q_ <= 256; }
      |                                                   ~~~^~~~~~
C:/Users/mohit/Documents/camera-streamer/main/main.cpp: In function 'void app_main()':
C:/Users/mohit/Documents/camera-streamer/main/main.cpp:131:3: warning: missing initializer for member 'camera_config_t::fb_location' [-Wmissing-field-initializers]
  131 |   };
      |   ^
C:/Users/mohit/Documents/camera-streamer/main/main.cpp:131:3: warning: missing initializer for member 'camera_config_t::sccb_i2c_port' [-Wmissing-field-initializers]`

After flashing the device, it does seem to boot up normally, but keeps waiting for wifi. `[Camera Streamer/I]:waiting for wifi connection...`

I thought it would go in AP mode, but I can't find any new SSID on my phone. Do I need to enter the wifi configuration somewhere before compiling?

**Comment by finger563** [comment]
Ah yes - it seems everything is good, but you should run `idf.py menuconfig` and set up the wireless network information which is under the top-level `Camera Streamer Configuration` menu.  I decided to make it a WiFi station instead of access point so that I could have multiple of them on a network and let a display or computer switch between them. That being said, `espp` does have a wifi access point component (or you can use esp-idf's wifi APIs if you like) to replace the wifi config in `main.cpp` with an access point if you like.

**Comment by finger563** [comment]
@moh1t Since it seems like you got it building I'm closing this issue. If you have any other issues feel free to open another issue :)
